# Image
FROM docker.io/library/alpine:latest

# copy setup scripts and precompiled programs
COPY scripts/* bins/* /usr/local/bin/

# copy configs
COPY configs/greet.fish /etc/fish/conf.d/

# Install the basics
RUN apk add --no-cache \
    fish git curl pfetch-rs

# Install host-spawn
#RUN curl -fsSL https://github.com/1player/host-spawn/releases/latest/download/host-spawn-x86_64 -o /usr/local/bin/host-spawn

# Switch to user
#USER root
