# Image
FROM docker.io/library/alpine:latest

#doas access/config and vscode user creation is disabled cuz we don need that cuh

# create vscode user
## reference: https://github.com/devcontainers/images/blob/main/src/base-alpine/.devcontainer/devcontainer.json
## reference: https://github.com/devcontainers/features/tree/main/src/common-utils
#RUN addgroup -S wheel
RUN addgroup -g 1000 vscode && \
    adduser -u 1000 -G vscode -D vscode && \
    addgroup vscode wheel && \
    groups vscode

# install and configure passwordless doas for :wheel
# also shadow package
RUN apk add --no-cache doas doas-sudo-shim shadow
COPY configs/doas.conf /etc/

# copy setup scripts and precompiled programs
COPY scripts/* /usr/local/bin/

# copy configs
COPY configs/customshi.fish /etc/fish/conf.d/
COPY configs/rust-path.fish.bak /etc/fish/conf.d/

# Install the basics
RUN apk add --no-cache fish git curl nano micro pfetch-rs

# Install host-spawn
RUN curl -fsSL https://github.com/1player/host-spawn/releases/latest/download/host-spawn-x86_64 \
    -o /usr/local/bin/host-spawn && \
    ln -s /usr/local/bin/host-spawn /usr/local/bin/hpwn

# Switch to user
USER vscode
